# Placeholder `setup-trellis-cli` action for deploying Trellis sites using multiple repositories
#
# ⚠️ This example assumes your theme is using Sage 10
#
# Replace `sage` with your theme folder
# Replace `example/example.com` with your github repository

name: Deploy site

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        path: site
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: yarn
        cache-dependency-path: site/web/app/themes/sage/yarn.lock
    - uses: actions/checkout@v2
      with:
        repository: example/example.com
        path: trellis
        token: ${{ secrets.TRELLIS_REPOSITORY_PERSONAL_ACCESS_TOKEN }}
    - uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.TRELLIS_DEPLOY_SSH_PRIVATE_KEY }}
        known_hosts: ${{ secrets.TRELLIS_DEPLOY_SSH_KNOWN_HOSTS }}
    - uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.TRELLIS_DEPLOY_SSH_PRIVATE_KEY }}
    - uses: roots/setup-trellis-cli@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        ansible-vault-password: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}
    - name: Deploy
      run: trellis deploy production
      working-directory: trellis
