name: Tests
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-node@v4
      with:
        node-version: 16.x
    - run: mkdir trellis
    - uses: ./
      with:
        ansible-vault-password: fake
        auto-init: false
        galaxy-install: false
        repo-token: ${{ secrets.GITHUB_TOKEN }}
  test-with-trellis:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-node@v4
      with:
        node-version: 16.x
    - run: git clone https://github.com/roots/trellis.git
    - uses: ./
      with:
        ansible-vault-password: fake
        repo-token: ${{ secrets.GITHUB_TOKEN }}
  test-with-trellis-no-galaxy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-node@v4
      with:
        node-version: 16.x
    - run: git clone https://github.com/roots/trellis.git
    - uses: ./
      with:
        ansible-vault-password: fake
        galaxy-install: false
        repo-token: ${{ secrets.GITHUB_TOKEN }}
  test-with-trellis-no-auto-init:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-node@v4
      with:
        node-version: 16.x
    - run: git clone https://github.com/roots/trellis.git
    - uses: ./
      with:
        ansible-vault-password: fake
        auto-init: false
        repo-token: ${{ secrets.GITHUB_TOKEN }}
  test-with-trellis-no-cache-virtualenv:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-node@v4
      with:
        node-version: 16.x
    - run: git clone https://github.com/roots/trellis.git
    - uses: ./
      with:
        ansible-vault-password: fake
        cache-virtualenv: false
        repo-token: ${{ secrets.GITHUB_TOKEN }}
  test-no-repo-token:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-node@v4
      with:
        node-version: 16.x
    - run: mkdir trellis
    - uses: ./
      with:
        ansible-vault-password: fake
        auto-init: false
        galaxy-install: false
